'use client'
import { useMemo,useState } from 'react'
import { useRouter } from 'next/navigation'
import { TAROT_DECK,TAROT_SPREADS,tarotCard,type TarotSpreadId } from './contracts'
import { createMobileTarotState,drawMobileTarotCard,selectMobileTarotSpread,toggleMobileTarotGuide,type MobileTarotDraw } from './mobile-state'
import { saveTarotHistoryRecord } from './local-history-browser'

function shuffled(){const a=TAROT_DECK.map(c=>c.id);for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j]!,a[i]!]}return a}
function labels(spread:TarotSpreadId,guide:boolean,count:number){const s=TAROT_SPREADS.find(x=>x.id===spread)!;const a=spread==='free'?Array.from({length:count},(_,i)=>`第${i+1}张`):[...s.slots];if(guide)a.push('指引');return a}
function Face({draw,style,faces}:{draw:MobileTarotDraw;style:'veil'|'orrery';faces:Array<{veil:string;orrery:string}>}){const index=TAROT_DECK.findIndex(card=>card.id===draw.cardId);const html=faces[index]?.[style]??'';return <div className="original-mobile-tarot-face" aria-label={tarotCard(draw.cardId)?.display}><div style={{transform:draw.reversed?'rotate(180deg)':'none'}}><div dangerouslySetInnerHTML={{__html:html}} /></div></div>}
export function MobileTarotClient({companionName,faces}:{companionName:string;faces:Array<{veil:string;orrery:string}>}){
 const router=useRouter();const [state,setState]=useState(()=>createMobileTarotState(shuffled()));const [sessionId,setSessionId]=useState(()=>crypto.randomUUID());const [style,setStyle]=useState<'veil'|'orrery'>('veil');const [loading,setLoading]=useState(false);const [reading,setReading]=useState('');const [notice,setNotice]=useState('');const [grant,setGrant]=useState<string|null>(null);const [history,setHistory]=useState<Array<{role:'user'|'assistant';content:string}>>([]);const [fuIndex,setFuIndex]=useState(0)
 const spread=TAROT_SPREADS.find(s=>s.id===state.spread)!;const slotLabels=useMemo(()=>labels(state.spread,state.guide,state.totalSlots),[state.spread,state.guide,state.totalSlots]);const full=state.slots.length>=state.totalSlots
 function reset(){if(loading)return;setState(createMobileTarotState(shuffled()));setSessionId(crypto.randomUUID());setReading('');setGrant(null);setHistory([]);setFuIndex(0);setNotice('')}
 async function interpret(){if(!full||loading)return;setLoading(true);setNotice('');try{const response=await fetch('/api/ai/tarot',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'reading',sessionId,spread:state.spread,guide:state.guide,cards:state.slots})});const body=await response.json() as Record<string,unknown>;if(!response.ok)throw new Error(typeof body.error==='string'?body.error:'Tarot AI 暂时没有回应。');const text=String(body.content||'');setReading(text);setHistory([{role:'assistant',content:text}]);setGrant(typeof body.followupGrant==='string'?body.followupGrant:null)}catch(e){setNotice(e instanceof Error?e.message:'Tarot AI 暂时没有回应。')}finally{setLoading(false)}}
 async function follow(type:'detail'|'summary'|'care'){if(!grant||fuIndex>=3||loading)return;const q=type==='detail'?'请更详细地解读每张牌的含义，以及它们之间的关联。':type==='summary'?'请用简洁的几句话总结这次占卜的核心信息。':'请以温柔关怀的语气，对我说一句安慰或鼓励的话。';setLoading(true);try{const response=await fetch('/api/ai/tarot',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'followup',sessionId,spread:state.spread,guide:state.guide,cards:state.slots,followupIndex:fuIndex,followupGrant:grant,history,question:q})});const body=await response.json() as Record<string,unknown>;if(!response.ok)throw new Error(typeof body.error==='string'?body.error:'追问失败');const text=String(body.content||'');setReading(v=>`${v}\n\n${text}`);setHistory(v=>[...v,{role:'user',content:q},{role:'assistant',content:text}]);setFuIndex(v=>v+1);setGrant(typeof body.followupGrant==='string'?body.followupGrant:null)}catch(e){setNotice(e instanceof Error?e.message:'追问失败')}finally{setLoading(false)}}
 async function save(){const now=Date.now(),ls=labels(state.spread,state.guide,state.slots.length);let content=`【塔罗占卜记录】\n牌阵：${spread.name}${state.guide?' + 指引牌':''}\n\n`;state.slots.forEach((d,i)=>{content+=`${ls[i]||''}：${tarotCard(d.cardId)?.display}（${d.reversed?'逆位':'正位'}）\n`});if(reading)content+=`\n【AI解读】\n${reading}\n`;await saveTarotHistoryRecord({id:`tarot_${now}`,title:`Tarot · ${spread.name}${state.guide?' + 指引牌':''}`,subtitle:`${companionName} · ${state.slots.length}张`,locked:true,category:'',content,created:now,updated:now});setNotice('占卜记录已保存到当前浏览器。')}
 return <main className="mobile-tarot-app"><header><button aria-label="返回" disabled={loading} onClick={()=>router.back()}>‹</button><h1>Tarot <small>占卜</small></h1><button aria-label="重新洗牌" disabled={loading} onClick={reset}>↻</button></header><section className="mobile-tarot-table"><div className="mobile-tarot-spreads">{TAROT_SPREADS.map(s=><button key={s.id} disabled={loading||Boolean(reading)} className={state.spread===s.id?'active':''} onClick={()=>{setState(selectMobileTarotSpread(state,s.id));setReading('')}}>{s.name}</button>)}</div><label className="mobile-tarot-guide"><input type="checkbox" disabled={loading||Boolean(reading)} checked={state.guide} onChange={e=>{setState(toggleMobileTarotGuide(state,e.target.checked));setReading('')}}/>＋指引牌 <span>{spread.desc}</span></label>{!reading?<div className="mobile-tarot-fan">{state.deck.map((id,i)=><button key={id} disabled={loading} className={state.slots.some(s=>s.cardId===id)?'picked':''} style={{left:`calc(50% + ${(i-38.5)*3.6}px - 30px)`,transform:`rotate(${(i-38.5)*.55}deg)`}} aria-label={`背牌 ${i+1}`} onClick={()=>setState(drawMobileTarotCard(state,i,Math.random()<.5))}>✦</button>)}</div>:null}<div className="mobile-tarot-slots">{Array.from({length:state.totalSlots},(_,i)=><div className="mobile-tarot-slot" key={i}>{state.slots[i]?<Face draw={state.slots[i]!} style={style} faces={faces}/>:null}<span>{slotLabels[i]}</span></div>)}</div>{reading?<div className="mobile-tarot-reading"><p>{reading}</p>{fuIndex<3&&grant?<div><button disabled={loading} onClick={()=>void follow('detail')}>详细解读</button><button disabled={loading} onClick={()=>void follow('summary')}>总结</button><button disabled={loading} onClick={()=>void follow('care')}>关怀</button></div>:null}<small>剩余追问 {3-fuIndex} 次</small></div>:null}<div className="mobile-tarot-actions"><button disabled={loading} onClick={reset}>Reshuffle</button><button disabled={loading} onClick={()=>setStyle(v=>v==='veil'?'orrery':'veil')}>Deck</button>{!reading&&full?<button disabled={loading} onClick={()=>void interpret()}>Invite AI</button>:null}<button disabled={loading} onClick={()=>void save()}>Save</button><button disabled={loading} onClick={()=>router.back()}>Exit</button></div>{loading?<p className="mobile-tarot-notice">✦ 正在解读…</p>:notice?<p className="mobile-tarot-notice">{notice}</p>:null}</section></main>
}
