export const PUBLIC_MOBILE_PATCH = `
  var continuumPrivateAppearance=new URLSearchParams(location.search).get('page')==='appearance';
  document.title = 'Keleoz Continuum';
  function removePublicLock() { document.querySelectorAll('#lockscr,#lk-preveil').forEach(function(lock){lock.remove()}); try { if (window._lkClockT) clearInterval(window._lkClockT); } catch (e) {} document.documentElement.classList.remove('sp-dark'); }
  function applyBranding() { removePublicLock(); var name = document.getElementById('dw-name'); if (name && name.textContent !== 'Keleoz') name.textContent = 'Keleoz'; var title = document.getElementById('tb-title'); if (title && !continuumPrivateAppearance && title.textContent !== 'Home') title.textContent = 'Home'; var profile = document.getElementById('pf-name'); if (profile && (!profile.textContent || profile.textContent.trim() === '—' || profile.textContent.trim() === 'Sui')) profile.textContent = 'Keleoz'; }
  applyBranding();
  var lockObserver = new MutationObserver(applyBranding); lockObserver.observe(document.documentElement,{childList:true,subtree:true}); window.setTimeout(function(){ lockObserver.disconnect(); applyBranding(); },4000);
  var style = document.getElementById('continuum-public-mobile-style');
  if (!style) { style = document.createElement('style'); style.id = 'continuum-public-mobile-style'; style.textContent = '#dw-name{font-family:var(--disp);letter-spacing:.06em}#drawer .dw-item[data-page="chat"],#drawer .dw-item[data-page="icode"],#drawer .dw-item[data-page="api"],#drawer .dw-item[data-page="diy"],#sec-profile-cal .sb-app[data-page="chat"],#sec-profile-cal .sb-app[data-page="icode"],#sec-profile-cal .sb-app[data-page="data"],#sec-profile-cal .sb-app[data-page="visual"],#sec-profile-cal .sb-app[data-page="diy"],#sb-calapp,#sb-setapp,#sb-frdapp{display:none!important}'; document.head.appendChild(style); }
  function ensureProjectTile() { if (document.querySelector('#sec-profile-cal .sb-app[data-page="projects"]')) return; var blog = document.querySelector('#sec-profile-cal .sb-app[data-page="blog"]'); if (!blog || !blog.parentNode) return; var template = document.createElement('template'); template.innerHTML = '<button class="sb-app" data-page="projects" data-dk="app:projects"><span class="sb-ic"><svg viewBox="0 0 24 24"><path d="M4 6.5h6l1.8 2H20v10.5H4z"/><path d="M7 13h10M7 16h7"/></svg></span><span class="sb-t">项目</span></button>'; blog.parentNode.insertBefore(template.content.firstElementChild, blog.nextSibling); if (window.DK_NAMES) window.DK_NAMES['app:projects']='项目'; }
  if(style)style.textContent+='#lockscr,#lk-preveil{display:none!important}';
  ensureProjectTile();
  var historyBlog=document.querySelector('#sec-profile-cal .sb-app[data-page="blog"]');
  if(historyBlog&&!document.querySelector('[data-page="local-history"]')){var historyTile=historyBlog.cloneNode(true);historyTile.dataset.page='local-history';historyTile.dataset.dk='app:local-history';historyTile.querySelector('.sb-t').textContent='本机存档';historyBlog.parentNode.insertBefore(historyTile,historyBlog.nextSibling);if(window.DK_NAMES)window.DK_NAMES['app:local-history']='本机存档'}
  function ensureTeaTile() { if (document.querySelector('#sec-profile-cal .sb-app[data-page="tea"]')) return; var music = document.getElementById('sb-musicapp'); if (!music || !music.parentNode) return; var template = document.createElement('template'); template.innerHTML = '<button class="sb-app" data-page="tea" data-dk="app:tea"><span class="sb-ic"><svg viewBox="0 0 24 24"><path d="M5 8h11v6a4 4 0 0 1-4 4H9a4 4 0 0 1-4-4z"/><path d="M16 10h1.5a2.5 2.5 0 0 1 0 5H16M8 5.5c0 1-.8 1.4-.8 2.3M11 4.5c0 1-.8 1.4-.8 2.3"/></svg></span><span class="sb-t">茶歇</span></button>'; music.parentNode.insertBefore(template.content.firstElementChild, music.nextSibling); if (window.DK_NAMES) window.DK_NAMES['app:tea']='茶歇'; }
  ensureTeaTile();
  function ensureStoryTile() { if (document.querySelector('#sec-profile-cal .sb-app[data-page="story"]')) return; var tea = document.querySelector('#sec-profile-cal .sb-app[data-page="tea"]'); if (!tea || !tea.parentNode) return; var template = document.createElement('template'); template.innerHTML = '<button class="sb-app" data-page="story" data-dk="app:story"><span class="sb-ic"><svg viewBox="0 0 24 24"><path d="M5 4.5h5.2A2.8 2.8 0 0 1 13 7.3V20a3.2 3.2 0 0 0-3-2H5z"/><path d="M19 4.5h-5.2A2.8 2.8 0 0 0 11 7.3V20a3.2 3.2 0 0 1 3-2h5z"/></svg></span><span class="sb-t">故事</span></button>'; tea.parentNode.insertBefore(template.content.firstElementChild, tea.nextSibling); if (window.DK_NAMES) window.DK_NAMES['app:story']='故事'; }
  ensureStoryTile();
  function ensureTarotTile() { if (document.querySelector('#sec-profile-cal .sb-app[data-page="tarot"]')) return; var story = document.querySelector('#sec-profile-cal .sb-app[data-page="story"]'); if (!story || !story.parentNode) return; var template = document.createElement('template'); template.innerHTML = '<button class="sb-app" data-page="tarot" data-dk="app:tarot"><span class="sb-ic"><svg viewBox="0 0 24 24"><path d="M12 3l2.3 5.2L20 10l-4.4 3.7L17 20l-5-3-5 3 1.4-6.3L4 10l5.7-1.8z"/></svg></span><span class="sb-t">占卜</span></button>'; story.parentNode.insertBefore(template.content.firstElementChild, story.nextSibling); if (window.DK_NAMES) window.DK_NAMES['app:tarot']='占卜'; }
  ensureTarotTile();
  function ensureCharacterTile() { if (document.querySelector('#sec-profile-cal .sb-app[data-page="character"]')) return; var tarot = document.querySelector('#sec-profile-cal .sb-app[data-page="tarot"]'); if (!tarot || !tarot.parentNode) return; var template = document.createElement('template'); template.innerHTML = '<button class="sb-app" data-page="character" data-dk="app:character"><span class="sb-ic"><svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3.2"/><path d="M6 20a6 6 0 0 1 12 0M8.5 13.5l-2.5-2M15.5 13.5l2.5-2"/></svg></span><span class="sb-t">角色</span></button>'; tarot.parentNode.insertBefore(template.content.firstElementChild, tarot.nextSibling); if (window.DK_NAMES) window.DK_NAMES['app:character']='角色'; }
  ensureCharacterTile();
  var timelineTile=document.getElementById('sb-calapp'); if(timelineTile){var timelineText=timelineTile.querySelector('.sb-t');if(timelineText)timelineText.textContent='时间线';if(window.DK_NAMES)window.DK_NAMES['app:calendar']='时间线';}
  if(timelineTile&&!document.getElementById('continuum-calendar-app')){var calendarTile=timelineTile.cloneNode(true);calendarTile.id='continuum-calendar-app';calendarTile.dataset.dk='app:owner-calendar';calendarTile.querySelector('.sb-t').textContent='日历';timelineTile.parentNode.insertBefore(calendarTile,timelineTile.nextSibling);if(window.DK_NAMES)window.DK_NAMES['app:owner-calendar']='日历';}
  var searchTile=document.querySelector('#sec-profile-cal .sb-app[data-page="guide"]'); if(searchTile){var searchText=searchTile.querySelector('.sb-t');if(searchText)searchText.textContent='搜索';if(window.DK_NAMES)window.DK_NAMES['app:guide']='搜索';}
  var timelineDrawer=document.querySelector('#drawer .dw-item[data-page="memory"]'); if(timelineDrawer){var timelineEn=timelineDrawer.querySelector('.dw-en'),timelineCn=timelineDrawer.querySelector('.dw-cn');if(timelineEn)timelineEn.textContent='Memory';if(timelineCn)timelineCn.textContent='记忆';}
  var searchDrawer=document.querySelector('#drawer .dw-item[data-page="guide"]'); if(searchDrawer){var searchEn=searchDrawer.querySelector('.dw-en'),searchCn=searchDrawer.querySelector('.dw-cn');if(searchEn)searchEn.textContent='Search';if(searchCn)searchCn.textContent='搜索';}
  if (typeof window.deskApplyLayout==='function') Promise.resolve(window.deskApplyLayout()).catch(function(){});
  function external(selector, href) { document.querySelectorAll(selector).forEach(function(el) { if (el.dataset.continuumBound) return; el.dataset.continuumBound='1'; el.addEventListener('click', function(ev) { ev.preventDefault(); ev.stopPropagation(); window.parent.location.href=href; }, true); }); }
  external('#drawer .dw-item[data-page="blog"],#sec-profile-cal .sb-app[data-page="blog"]','/blog');
  external('#sec-profile-cal .sb-app[data-page="local-history"]','/history');
  external('#sec-profile-cal .sb-app[data-page="projects"]','/projects');
  var momentsTile=document.querySelector('#sec-profile-cal .sb-app[data-page="beyond"] .sb-t'); if(momentsTile) momentsTile.textContent='动态';
  external('#drawer .dw-item[data-page="beyond"],#sec-profile-cal .sb-app[data-page="beyond"]','/moments');
  external('#sec-profile-cal .sb-app[data-page="space"]','/about');
  external('#drawer .dw-item[data-page="letters"],#sec-profile-cal .sb-app[data-page="letters"]','/letters');
  external('#sec-profile-cal .sb-app[data-page="tea"]','/tea');
  external('#sec-profile-cal .sb-app[data-page="story"]','/story');
  external('#sec-profile-cal .sb-app[data-page="tarot"]','/tarot');
  external('#sec-profile-cal .sb-app[data-page="character"]','/character');
  external('#drawer .dw-item[data-page="memory"],#sec-profile-cal .sb-app[data-page="memory"]','/memory');
  external('#drawer .dw-item[data-page="chat"],#sec-profile-cal .sb-app[data-page="chat"]','/chat');
  external('#sb-calapp','/timeline');
  external('#continuum-calendar-app','/calendar');
  if(style)style.textContent+='#drawer .dw-item[data-page="chat"],#sec-profile-cal .sb-app[data-page="chat"],#sb-calapp{display:flex!important}';
  if(style)style.textContent+='#sec-profile-cal .sb-app.dk-hidden{display:none!important}';
  external('#drawer .dw-item[data-page="guide"],#sec-profile-cal .sb-app[data-page="guide"]','/search');
  try { if (typeof DOCKS !== 'undefined' && Array.isArray(DOCKS.profile)) { DOCKS.profile = DOCKS.profile.filter(function(item){ return item.k !== 'api' && item.k !== 'set'; }); if (typeof renderDock === 'function') renderDock(); } } catch (e) {}
  if (new URLSearchParams(window.parent.location.search).get('openMusic') === '1') window.setTimeout(function(){ document.getElementById('sb-musicapp')?.click(); },900);
`
